# Generated by Django 5.1.5 on 2025-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selling_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField()),
                ('card_number', models.CharField()),
                ('pin', models.CharField()),
                ('giftcard_type', models.CharField()),
                ('expiry', models.DateField(default='2025-12-31')),
                ('giftcard_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('sold', 'Sold')], default='pending', max_length=10)),
            ],
        ),
    ]
