# Generated by Django 5.1.5 on 2025-01-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SwapCards', '0002_purchase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='SwapCards_purchase',
        ),
    ]
