# Generated by Django 5.1.5 on 2025-01-30 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapCards', '0003_alter_purchase_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling_info',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selling_info',
            name='giftcard_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='selling_info',
            name='pin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selling_info',
            name='username1',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='PurchasedGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('giftcard_type', models.CharField(max_length=100)),
                ('expiry', models.DateField()),
                ('giftcard_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
